import { Config } from "effect"

function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const OPENCRAFT_EXPERIMENTAL = truthy("OPENCRAFT_EXPERIMENTAL")
const copy = process.env["OPENCRAFT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENCRAFT_AUTO_HEAP_SNAPSHOT: truthy("OPENCRAFT_AUTO_HEAP_SNAPSHOT"),
  OPENCRAFT_GIT_BASH_PATH: process.env["OPENCRAFT_GIT_BASH_PATH"],
  OPENCRAFT_CONFIG: process.env["OPENCRAFT_CONFIG"],
  OPENCRAFT_CONFIG_CONTENT: process.env["OPENCRAFT_CONFIG_CONTENT"],
  OPENCRAFT_DISABLE_AUTOUPDATE: truthy("OPENCRAFT_DISABLE_AUTOUPDATE"),
  OPENCRAFT_ALWAYS_NOTIFY_UPDATE: truthy("OPENCRAFT_ALWAYS_NOTIFY_UPDATE"),
  OPENCRAFT_DISABLE_PRUNE: truthy("OPENCRAFT_DISABLE_PRUNE"),
  OPENCRAFT_DISABLE_TERMINAL_TITLE: truthy("OPENCRAFT_DISABLE_TERMINAL_TITLE"),
  OPENCRAFT_SHOW_TTFD: truthy("OPENCRAFT_SHOW_TTFD"),
  OPENCRAFT_DISABLE_AUTOCOMPACT: truthy("OPENCRAFT_DISABLE_AUTOCOMPACT"),
  OPENCRAFT_DISABLE_MODELS_FETCH: truthy("OPENCRAFT_DISABLE_MODELS_FETCH"),
  OPENCRAFT_DISABLE_MOUSE: truthy("OPENCRAFT_DISABLE_MOUSE"),
  OPENCRAFT_FAKE_VCS: process.env["OPENCRAFT_FAKE_VCS"],
  OPENCRAFT_SERVER_PASSWORD: process.env["OPENCRAFT_SERVER_PASSWORD"],
  OPENCRAFT_SERVER_USERNAME: process.env["OPENCRAFT_SERVER_USERNAME"],

  // Experimental
  OPENCRAFT_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENCRAFT_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCRAFT_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENCRAFT_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENCRAFT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("OPENCRAFT_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENCRAFT_MODELS_URL: process.env["OPENCRAFT_MODELS_URL"],
  OPENCRAFT_MODELS_PATH: process.env["OPENCRAFT_MODELS_PATH"],
  OPENCRAFT_DB: process.env["OPENCRAFT_DB"],

  OPENCRAFT_WORKSPACE_ID: process.env["OPENCRAFT_WORKSPACE_ID"],
  OPENCRAFT_EXPERIMENTAL_WORKSPACES: OPENCRAFT_EXPERIMENTAL || truthy("OPENCRAFT_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OPENCRAFT_DISABLE_PROJECT_CONFIG() {
    return truthy("OPENCRAFT_DISABLE_PROJECT_CONFIG")
  },
  get OPENCRAFT_TUI_CONFIG() {
    return process.env["OPENCRAFT_TUI_CONFIG"]
  },
  get OPENCRAFT_CONFIG_DIR() {
    return process.env["OPENCRAFT_CONFIG_DIR"]
  },
  get OPENCRAFT_PURE() {
    return truthy("OPENCRAFT_PURE")
  },
  get OPENCRAFT_PERMISSION() {
    return process.env["OPENCRAFT_PERMISSION"]
  },
  get OPENCRAFT_PLUGIN_META_FILE() {
    return process.env["OPENCRAFT_PLUGIN_META_FILE"]
  },
  get OPENCRAFT_CLIENT() {
    return process.env["OPENCRAFT_CLIENT"] ?? "cli"
  },
}
